### ISSUE TITLE
SafeConfigParser alias has been deprecated

### ISSUE THREAD

**Issue by johnthagen** [drmikehenry/svnwrap#20]
See https://docs.python.org/3/whatsnew/3.2.html#configparser

A `DeprecationWarning` is generated:

```
The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
```

Not sure an easy way around this while maintaining compatibility with Python 2, however.

I found out about this because PyCharm will ~~strikethrough~~ functions that raise `DeprecationWarning`'s.

**Comment by drmikehenry** [comment]
Thanks for the note.  I've updated the tests to display deprecation warnings and reworked the imports to use the preferred class (ConfigParser or SafeConfigParser) based on the Python version.
