### ISSUE TITLE
testsvn.py does not appear to be tested by pytest / CI

### ISSUE THREAD

**Issue by johnthagen** [drmikehenry/svnwrap#28]
Is testsvn.py designed to only be run manually? As best I can tell, it won't be picked up automatically by `pytest`'s discovery (which looks for files and functions with `test` in the front (or `unittest` style classes)).

It would probably be best to refactor this into a `pytest` style test, and put it into the `test` folder: https://docs.pytest.org/en/latest/

**Comment by drmikehenry** [comment]
`testsvn.py` would perhaps be better named `fakesvn.py`.  It's a dummy implementation of the `svn` client binary that generates canned output in response to a few Subversion subcommands like `st`.  It's used for manual testing of `svnwrap` something like this:

    svnwrap --svn testsvn.py st

There is currently no code for verifying that the colorized output from `svnwrap` is correct given the fake data generated by `testsvn.py`.  Additionally, `testsvn.py` doesn't know how to generate much variety of output.    While I like the idea of automation for this kind of testing, the payoff hasn't yet seemed worth the effort.

**Comment by johnthagen** [comment]
Ah, that's good to know - makes sense. Thanks for the clarification.
